### ISSUE TITLE
Shiro session

### ISSUE THREAD

**Issue by alabotski** [alejandro-du/shiro-vaadin-integration#8]
I have error with shiro sessions =((

```
Mar 13, 2019 2:37:45 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [TestConsole] in context with path [/test_console] threw exception [com.vaadin.flow.server.ServiceException: java.lang.IllegalMonitorStateException] with root cause
java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
        at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
        at com.vaadin.flow.server.VaadinService.unlockSession(VaadinService.java:787)
        at com.vaadin.flow.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:806)
        at com.vaadin.flow.server.VaadinService.findVaadinSession(VaadinService.java:662)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1501)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:242)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

My shiro.ini

```
[main]
authc.loginUrl = /
vaadin = org.vaadin.shiro.VaadinNavigationRolesAuthorizationFilter
vaadin.loginUrl = /

jdbiRealm = test.config.JdbiRealm
authcBasic.applicationName = test_cloud

sessionIdCookie=org.apache.shiro.web.servlet.SimpleCookie
sessionManager=org.apache.shiro.web.session.mgt.DefaultWebSessionManager
sessionIdCookie.name=sid
sessionIdCookie.maxAge=1800
sessionIdCookie.httpOnly=true
sessionManager.sessionIdCookie=$sessionIdCookie
sessionManager.sessionIdCookieEnabled=true
securityManager.sessionManager=$sessionManager

sessionListener1=test.listener.SessionListener1
sessionListener2=test.listener.SessionListener2
sessionManager.sessionListeners=$sessionListener1,$sessionListener2

sessionDAO=test.config.SessionDao
sessionIdGenerator=org.apache.shiro.session.mgt.eis.JavaUuidSessionIdGenerator
sessionDAO.sessionIdGenerator=$sessionIdGenerator
sessionManager.sessionDAO=$sessionDAO

#cacheManager = org.apache.shiro.cache.ehcache.EhCacheManager
#cacheManager.cacheManagerConfigFile=classpath:ehcache.xml
#securityManager.cacheManager = $cacheManager

#sessionManager.globalSessionTimeout=1800000
#sessionManager.sessionValidationSchedulerEnabled=true
#sessionValidationScheduler=org.apache.shiro.session.mgt.ExecutorServiceSessionValidationScheduler
#sessionValidationScheduler.interval = 100000
#sessionValidationScheduler.sessionManager=$sessionManager

#sessionValidationScheduler=org.apache.shiro.session.mgt.quartz.QuartzSessionValidationScheduler
#sessionValidationScheduler.sessionValidationInterval = 10000
#sessionValidationScheduler.sessionManager=$sessionManager

#sessionManager.sessionValidationScheduler=$sessionValidationScheduler
#sessionManager.deleteInvalidSessions=true

#sessionFactory=org.apache.shiro.session.mgt.OnlineSessionFactory
#sessionManager.sessionFactory=$sessionFactory

#securityManager.subjectDAO.sessionStorageEvaluator.sessionStorageEnabled = false

[users]
admin@admin.com = 1@QWaszx, admin

[roles]
admin = *

[urls]
/ = anon
/signup = anon, vaadin
/forgot-password = anon, vaadin
/reset-password = anon, vaadin
/registration-complete = anon, vaadin
/create-account = anon, vaadin
/payment = anon, vaadin
/environment = authc, vaadin[admin]
/billing = authc, vaadin[admin]
/settings = authc, vaadin[admin]
/api/cas/login = anon
/api/cas/userInfo = noSessionCreation, authcBasic
```

SessionDao
```
@Slf4j
public class SessionDao extends CachingSessionDAO {

  private static final SessionService sessionService = SessionServiceImpl.instance();

  @Override
  protected Serializable doCreate(Session session) {
    Serializable sessionId = generateSessionId(session);
    assignSessionId(session, sessionId);

    log.info("doCreate session id = {}", session.getId().toString());
    SessionDto sessionDto = SessionDto.builder()
        .id(session.getId().toString())
        .session(SerializableUtils.serialize(session))
        .host(session.getHost())
        .lastAccessTime(session.getLastAccessTime().toInstant())
        .startTimestamp(session.getStartTimestamp().toInstant())
        .timeout(session.getTimeout())
        .build();
    sessionService.createSession(sessionDto);
    return session.getId();
  }

  @Override
  protected void doUpdate(Session session) {
    if (session instanceof ValidatingSession && !((ValidatingSession) session).isValid()) {
      return; //If the session expires/stops, there is no need to update it again.
    }
    log.info("doUpdate session id = {}", session.getId().toString());
    SessionDto sessionDto = SessionDto.builder()
        .id(session.getId().toString())
        .session(SerializableUtils.serialize(session))
        .host(session.getHost())
        .lastAccessTime(session.getLastAccessTime().toInstant())
        .startTimestamp(session.getStartTimestamp().toInstant())
        .timeout(session.getTimeout())
        .build();
    sessionService.updateSession(sessionDto);
  }

  @Override
  protected void doDelete(Session session) {
    log.info("doDelete session id = {}", session.getId().toString());
    SessionDto sessionDto = SessionDto.builder()
        .id(session.getId().toString())
        .session(SerializableUtils.serialize(session))
        .host(session.getHost())
        .lastAccessTime(session.getLastAccessTime().toInstant())
        .startTimestamp(session.getStartTimestamp().toInstant())
        .timeout(session.getTimeout())
        .build();
    sessionService.deleteSession(sessionDto);
  }

  @Override
  protected Session doReadSession(Serializable sessionId) {
    log.info("doReadSession session id = {}", sessionId.toString());
    SessionDto sessionDto = sessionService.getSessionById(sessionId.toString());
    if (sessionDto == null) {
      return null;
    }
    return SerializableUtils.deserialize(sessionDto.getSession());
  }
}
```

**Comment by alabotski** [comment]
I found one article 
http://mikepilone.blogspot.com/2013/07/vaadin-shiro-and-push.html

but
`
VaadinSession vaadinSession = VaadinSession.getCurrent();`

Always null...

**Comment by alejandro-du** [comment]
Are you able to provide a compilable and runnable reduced test case so I can easily reproduce the issue and investigate?

**Comment by alabotski** [comment]
Can I take some time? I'm in hospital now

**Comment by alejandro-du** [comment]
Oh, I hope you are okay.
